---
- name: Create prometheus group
  ansible.builtin.group:
    state: present
    name: prometheus
    system: yes
  tags:
    - prometheus
    - prometheus_system

- name: Create prometheus user
  ansible.builtin.user:
    state: present
    name: prometheus
    group: prometheus
    system: yes
    create_home: no
    home: /var/lib/prometheus
    shell: /usr/sbin/nologin
    password: "*"
  tags:
    - prometheus
    - prometheus_system

- name: Create /var/lib/prometheus
  ansible.builtin.file:
    owner: prometheus
    group: prometheus
    mode: '0755'
    state: directory
    dest: /var/lib/prometheus
  tags:
    - prometheus
    - prometheus_system

- name: Create Prometheus config dir
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    dest: /etc/prometheus
  tags:
    - prometheus
    - prometheus_system
    - prometheus_config

- name: Set Prometheus config
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    src: prometheus.config.yml
    dest: /etc/prometheus/prometheus.yml
  tags:
    - prometheus
    - prometheus_config

- name: Create Prometheus targets dir
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    dest: /etc/prometheus/targets.d
  tags:
    - prometheus
    - prometheus_system
    - prometheus_config

- name: Set targets file
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    src: prometheus.targets.yml
    dest: /etc/prometheus/targets.d/node.yml
  tags:
    - prometheus
    - prometheus_config

- name: Install Prometheus
  script: scripts/install-prometheus
  args:
    creates: /usr/local/bin/prometheus
  tags:
    - prometheus
    - prometheus_install

- name: Set /lib/systemd/system/prometheus.service
  ansible.builtin.copy:
    owner: root
    group: root
    mode: '0644'
    src: prometheus.service
    dest: /lib/systemd/system/prometheus.service
  tags:
    - prometheus
    - prometheus_service

- name: Start and enable Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus
    - prometheus_service
