---
global:
  scrape_interval: 30s
  evaluation_interval: 30s

  # external_labels:
  #    monitor: example

# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: [localhost:9093]

rule_files: []
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: [localhost:9090]

  - job_name: localnode
    static_configs:
      - targets: [localhost:9100]

  - job_name: grafana
    static_configs:
      - targets: [localhost:3000]

  - job_name: node
    file_sd_configs:
      - files: [/etc/prometheus/targets.d/node.yml]
